import type System from "../System";

export default (image: System): string => {
    const reader = image.getReader()
    return `# This Containerfile was automagically generated by Joscfg-ostree. Don't modify it!\n \n# Grab the base image.\nFROM ${reader.fullChannelBaseURI}\n`
}